### ISSUE TITLE
Error for Undefined symbols

### ISSUE THREAD

**Issue by raymondchau-sinodynamic** [OlehKulykov/NSDictionary-SafeGetters#1]
When compiled, I see these errors:

Undefined symbols for architecture x86_64:
  "___gxx_personality_v0", referenced from:
      -[NSDictionary(SafeGetters) integerForKey:] in libNSDictionary+SafeGetters.a(NSDictionary+SafeGetters.o)
      -[NSDictionary(SafeGetters) unsignedIntegerForKey:] in libNSDictionary+SafeGetters.a(NSDictionary+SafeGetters.o)
      -[NSDictionary(SafeGetters) int64ForKey:] in libNSDictionary+SafeGetters.a(NSDictionary+SafeGetters.o)
      -[NSDictionary(SafeGetters) uint64ForKey:] in libNSDictionary+SafeGetters.a(NSDictionary+SafeGetters.o)
      -[NSDictionary(SafeGetters) doubleForKey:] in libNSDictionary+SafeGetters.a(NSDictionary+SafeGetters.o)
      -[NSDictionary(SafeGetters) floatForKey:] in libNSDictionary+SafeGetters.a(NSDictionary+SafeGetters.o)
      -[NSDictionary(SafeGetters) cgFloatForKey:] in libNSDictionary+SafeGetters.a(NSDictionary+SafeGetters.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I  tried to add libstdc++ to the project frameworks, which can fix the issue.
Will there be a better solution for adding c++ library to podspec?

reference here:
http://stackoverflow.com/questions/16593292/cocoapods-linking-with-c-symbols-defined-in-libpods-a

**Comment by OlehKulykov** [comment]
Hello, yes it's added to podspec.
Thank you.
